server:
  port: 80

#dubbo
dubbo:
  #?????????
  application:
    name: health_mobile
  #??????
  registry:
    address: zookeeper://127.0.0.1:2181
  #?????? 10??
  #check=false ??????????????????false
  #check=true ?????????????????????????
  consumer:
    timeout: 600000
    check: false
spring:
  redis:
    host: 127.0.0.1
  #????
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  #??????
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8